server:
  port: 10086
spring:
  application:
eureka:
  client:
    fetch-registry: true #不从注册中心拉取注册表
    register-with-eureka: true #不将自己注册到注册中心
    service-url:
      defaultZone: http://localhost:10086/eureka
