server:
  port: 80
spring:
  application:
    name: lianxi-service
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  jpa:
      show-sql: true
      hibernate:
        ddl-auto: update
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    fetch-registry: false #从不注册中心拉取注册表